### ISSUE TITLE
checkpoints would be public?

### ISSUE THREAD

**Issue by deyituo** [aask1357/hilcodec#2]
I find onnx model with 8 qualitizers is public, but 12 in the configs, would you public the full checkpoints?

**Comment by aask1357** [comment]
We added the `hilcodec_music` checkpoint (a model trained on general audio), which has 12 quantizers.
`hilcodec_speech` (a model trained on clean speech) has 8 quantizers, which is the default configuration. This is because we found that for clean speech only, 8 quantizers (6kbps @ 24kHz) is enough.
We'll update the `configs/hilcodec_speech.yaml` file to have 8 quantizers as default. Thank you!

**Comment by deyituo** [comment]
Thanks for your reply!
